In [239]:
import numpy as np
import pandas as pd
import math
from numpy import mean

In [240]:
df = pd.read_csv('data (1).csv')

In [241]:
y = df['y'].values.reshape(-1,1).astype('float32')
m = mean(y)
X = np.array([m for i in range(0, 200)])

In [242]:
# Null model
from sklearn.model_selection import KFold
MSE_10fold_null = []
MSE_10fold_null_test = []
rss = 0
tss = 0
tss_test = 0
cv_10fold = KFold(n_splits=10, random_state=10, shuffle=True)
for train, test in cv_10fold.split(X):
    #print(test)
    x_train_10fold, x_test_10fold = X[train], X[test]
    y_train_10fold, y_test_10fold = y[train], y[test]
    fitted_y_10fold = m
    #print(fitted_y_10fold)
    rss += (fitted_y_10fold - mean(y)) ** 2
    tss += (y_train_10fold - mean(y)) ** 2
    tss_test += (y_test_10fold - mean(y)) ** 2
    MSE_10fold_null.append((y_train_10fold-fitted_y_10fold)**2)
    MSE_10fold_null_test.append((y_test_10fold-fitted_y_10fold)**2)
RMSE_null = math.sqrt(np.mean(MSE_10fold_null))
E_RMSE_null_test = math.sqrt(np.mean(MSE_10fold_null_test))
R2_null = mean(rss)/mean(tss)
E_R2_null_test = mean(rss)/mean(tss_test)
print("Estimated RMSE via 10-fold CV =",RMSE_null)
print("Estimated R^2 via 10-fold CV =",R2_null)
print("Estimated E(RMSEtest) via 10-fold CV =",E_RMSE_null_test)
print("Estimated E(R^2 test) via 10-fold CV =",E_R2_null_test)

Estimated RMSE via 10-fold CV = 4.7176467919569935
Estimated R^2 via 10-fold CV = 0.0
Estimated E(RMSEtest) via 10-fold CV = 4.7176467919569935
Estimated E(R^2 test) via 10-fold CV = 0.0


In [243]:
y = df['y'].values.reshape(-1,1).astype('float32')
#X = df[['x1','x2','x3','x4','x5']]
X = df[['x1','x2','x3','x4','x5']].values.reshape(-1,5).astype('float32')

In [244]:
# Full model
from sklearn.linear_model import LinearRegression
full_model = LinearRegression(fit_intercept=True, normalize=True).fit(X, y)
bs_full = full_model.coef_
b0_full = full_model.intercept_
bh_full = sum(abs(bs_full[0]))

In [245]:
MSE_10fold_full = []
MSE_10fold_full_test = []
rss = 0
tss = 0
tss_test = 0
cv_10fold = KFold(n_splits=10, random_state=10, shuffle=True)
for train, test in cv_10fold.split(X):
    #print(X)
    x_train_10fold, x_test_10fold = X[train], X[test]
    y_train_10fold, y_test_10fold = y[train], y[test]
    #print(x_train_10fold)
    fitted_y_10fold = b0_full + bs_full[0] @ x_train_10fold.T
    #fitted_y_10fold = b0_full + bs_full[0][1]*x_train_10fold[0] + bs_full[0][1]*x_train_10fold[1] + bs_full[0][2]*x_train_10fold[2] + bs_full[0][3]*x_train_10fold[3] + bs_full[0][4]*x_train_10fold[4]
    #print(fitted_y_10fold)
    rss += (fitted_y_10fold - mean(y)) ** 2
    tss += (y_train_10fold - mean(y)) ** 2
    tss_test += (y_test_10fold - mean(y)) ** 2
    MSE_10fold_full.append((y_train_10fold-fitted_y_10fold)**2)
    MSE_10fold_full_test.append((y_test_10fold-fitted_y_10fold)**2)
RMSE_full = math.sqrt(np.mean(MSE_10fold_full))
E_RMSE_full_test = math.sqrt(np.mean(MSE_10fold_full_test))
R2_full = mean(rss)/mean(tss)
E_R2_full_test = mean(rss)/mean(tss_test)
print("Estimated RMSE via 10-fold CV =",RMSE_full)
print("Estimated R^2 via 10-fold CV =",R2_full)
print("Estimated E(RMSEtest) via 10-fold CV =",E_RMSE_full_test)
print("Estimated E(R^2 test) via 10-fold CV =",E_R2_full_test)

Estimated RMSE via 10-fold CV = 6.029924474341263
Estimated R^2 via 10-fold CV = 0.63473547
Estimated E(RMSEtest) via 10-fold CV = 6.048960244864014
Estimated E(R^2 test) via 10-fold CV = 0.6347354


In [246]:
# LASSO (LassoCV10)
from sklearn import linear_model
clf = linear_model.Lasso()
clf.fit(X, y)
bs_lasso = clf.coef_
b0_lasso = clf.intercept_
bh_lasso = sum(abs(bs_lasso))

In [247]:
MSE_10fold_lasso = []
MSE_10fold_lasso_test = []
rss = 0
tss = 0
tss_test = 0
cv_10fold = KFold(n_splits=10, random_state=10, shuffle=True)
for train, test in cv_10fold.split(X):
    #print(X)
    x_train_10fold, x_test_10fold = X[train], X[test]
    y_train_10fold, y_test_10fold = y[train], y[test]
    #print(x_train_10fold)
    fitted_y_10fold = b0_full + bs_lasso @ x_train_10fold.T
    #fitted_y_10fold = b0_full + bs_full[0][1]*x_train_10fold[0] + bs_full[0][1]*x_train_10fold[1] + bs_full[0][2]*x_train_10fold[2] + bs_full[0][3]*x_train_10fold[3] + bs_full[0][4]*x_train_10fold[4]
    #print(fitted_y_10fold)
    rss += (fitted_y_10fold - mean(y)) ** 2
    tss += (y_train_10fold - mean(y)) ** 2
    tss_test += (y_test_10fold - mean(y)) ** 2
    MSE_10fold_lasso.append((y_train_10fold-fitted_y_10fold)**2)
    MSE_10fold_lasso_test.append((y_test_10fold-fitted_y_10fold)**2)
RMSE_lasso = math.sqrt(np.mean(MSE_10fold_lasso))
E_RMSE_lasso_test = math.sqrt(np.mean(MSE_10fold_lasso_test))
R2_lasso = mean(rss)/mean(tss)
E_R2_lasso_test = mean(rss)/mean(tss_test)
print("Estimated RMSE via 10-fold CV =",RMSE_lasso)
print("Estimated R^2 via 10-fold CV =",R2_lasso)
print("Estimated E(RMSEtest) via 10-fold CV =",E_RMSE_lasso_test)
print("Estimated E(R^2 test) via 10-fold CV =",E_R2_lasso_test)

Estimated RMSE via 10-fold CV = 5.255187242186472
Estimated R^2 via 10-fold CV = 0.24147923
Estimated E(RMSEtest) via 10-fold CV = 5.268112364860296
Estimated E(R^2 test) via 10-fold CV = 0.2414792


In [248]:
# LASSO (YourCV10 w/ rescaling)
from sklearn.linear_model import LassoCV
from sklearn.datasets import make_regression
#X, y = make_regression(noise=4, random_state=0)
lambdas = np.linspace(0, 0.1, 101)
#LassoCV(alphas = lambdas, cv = KFold(n_splits = 10, shuffle = True, random_state = 10))
reg = LassoCV(alphas = lambdas, cv=KFold(n_splits = 10, shuffle = True, random_state = 10), normalize = True).fit(X, y)
bs_yourlasso = reg.coef_
b0_yourlasso = reg.intercept_
alpha_w = reg.alpha_
bh_w = sum(abs(bs_yourlasso))

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:526: UserWarning: Coordinate descent with alpha=0 may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:526: UserWarning: Coordinate descent with alpha=0 may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:526: UserWarning: Coordinate descent with alpha=0 may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.8/site

In [249]:
MSE_10fold_lasso_w = []
MSE_10fold_lasso_w_test = []
rss = 0
tss = 0
tss_test = 0
cv_10fold = KFold(n_splits=10, random_state=10, shuffle=True)
for train, test in cv_10fold.split(X):
    #print(X)
    x_train_10fold, x_test_10fold = X[train], X[test]
    y_train_10fold, y_test_10fold = y[train], y[test]
    #print(x_train_10fold)
    fitted_y_10fold = b0_full + bs_yourlasso @ x_train_10fold.T
    #fitted_y_10fold = b0_full + bs_full[0][1]*x_train_10fold[0] + bs_full[0][1]*x_train_10fold[1] + bs_full[0][2]*x_train_10fold[2] + bs_full[0][3]*x_train_10fold[3] + bs_full[0][4]*x_train_10fold[4]
    #print(fitted_y_10fold)
    rss += (fitted_y_10fold - mean(y)) ** 2
    tss += (y_train_10fold - mean(y)) ** 2
    tss_test += (y_test_10fold - mean(y)) ** 2
    MSE_10fold_lasso_w.append((y_train_10fold-fitted_y_10fold)**2)
    MSE_10fold_lasso_w_test.append((y_test_10fold-fitted_y_10fold)**2)
RMSE_lasso_w = math.sqrt(np.mean(MSE_10fold_lasso_w))
E_RMSE_lasso_w_test = math.sqrt(np.mean(MSE_10fold_lasso_w_test))
R2_lasso_w = mean(rss)/mean(tss)
E_R2_lasso_w_test = mean(rss)/mean(tss_test)
print("Estimated RMSE via 10-fold CV =",RMSE_lasso_w)
print("Estimated R^2 via 10-fold CV =",R2_lasso_w)
print("Estimated E(RMSEtest) via 10-fold CV =",E_RMSE_lasso_w_test)
print("Estimated E(R^2 test) via 10-fold CV =",E_R2_lasso_w_test)

Estimated RMSE via 10-fold CV = 5.914790361934628
Estimated R^2 via 10-fold CV = 0.572884
Estimated E(RMSEtest) via 10-fold CV = 5.933071693623774
Estimated E(R^2 test) via 10-fold CV = 0.57288396


In [250]:
# LASSO (YourCV10 w/o rescaling)
reg = LassoCV(alphas = lambdas, cv=KFold(n_splits = 10, shuffle = True, random_state = 10), normalize = False).fit(X, y)
bs_wo = reg.coef_
b0_wo = reg.intercept_
alpha_wo = reg.alpha_
bh_wo = sum(abs(bs_wo))

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:526: UserWarning: Coordinate descent with alpha=0 may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:526: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 730.28564453125, tolerance: 0.39561405777931213
  model = cd_fast.enet_coordinate_descent_gram(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:526: UserWarning: Coordinate descent with alpha=0 may lead to unexpected results and is discouraged.
  model = cd_fa

In [251]:
MSE_10fold_lasso_wo = []
MSE_10fold_lasso_wo_test = []
rss = 0
tss = 0
tss_test = 0
cv_10fold = KFold(n_splits=10, random_state=10, shuffle=True)
for train, test in cv_10fold.split(X):
    #print(X)
    x_train_10fold, x_test_10fold = X[train], X[test]
    y_train_10fold, y_test_10fold = y[train], y[test]
    #print(x_train_10fold)
    fitted_y_10fold = b0_full + bs_wo @ x_train_10fold.T
    #fitted_y_10fold = b0_full + bs_full[0][1]*x_train_10fold[0] + bs_full[0][1]*x_train_10fold[1] + bs_full[0][2]*x_train_10fold[2] + bs_full[0][3]*x_train_10fold[3] + bs_full[0][4]*x_train_10fold[4]
    #print(fitted_y_10fold)
    rss += (fitted_y_10fold - mean(y)) ** 2
    tss += (y_train_10fold - mean(y)) ** 2
    tss_test += (y_test_10fold - mean(y)) ** 2
    MSE_10fold_lasso_wo.append((y_train_10fold-fitted_y_10fold)**2)
    MSE_10fold_lasso_wo_test.append((y_test_10fold-fitted_y_10fold)**2)
RMSE_lasso_wo = math.sqrt(np.mean(MSE_10fold_lasso_wo))
E_RMSE_lasso_wo_test = math.sqrt(np.mean(MSE_10fold_lasso_wo_test))
R2_lasso_wo = mean(rss)/mean(tss)
E_R2_lasso_wo_test = mean(rss)/mean(tss_test)
print("Estimated RMSE via 10-fold CV =",RMSE_lasso_wo)
print("Estimated R^2 via 10-fold CV =",R2_lasso_wo)
print("Estimated E(RMSEtest) via 10-fold CV =",E_RMSE_lasso_wo_test)
print("Estimated E(R^2 test) via 10-fold CV =",E_R2_lasso_wo_test)

Estimated RMSE via 10-fold CV = 5.9300496791154576
Estimated R^2 via 10-fold CV = 0.5810127
Estimated E(RMSEtest) via 10-fold CV = 5.948427765149146
Estimated E(R^2 test) via 10-fold CV = 0.58101267


In [252]:
table1 = pd.DataFrame(
    np.array([['Null', m, 'NA', 'NA', 'NA', 'NA', 'NA'],
              ['Full', b0_full[0], bs_full[0][0], bs_full[0][1], bs_full[0][2], bs_full[0][3], bs_full[0][4]],
              ['LASSO (LassoCV)', b0_lasso[0], bs_lasso[0], bs_lasso[1], bs_lasso[2], bs_lasso[3], bs_lasso[4]],
              ['LASSO (YourCV10 w/ rescaling)', b0_yourlasso, bs_yourlasso[0], bs_yourlasso[1], bs_yourlasso[2], bs_yourlasso[3], bs_yourlasso[4]],
              ['LASSO (YourCV10 w/o rescaling)', b0_wo, bs_wo[0], bs_wo[1], bs_wo[2], bs_wo[3], bs_wo[4]]]),
    columns=['Coefficients','b0','b1','b2','b3','b4','b5'])
table1

Coefficients            b0          b1         b2  \
0                            Null    0.24769504          NA         NA   
1                            Full   -0.07712214   1.0834538  1.8923526   
2                 LASSO (LassoCV)     0.0769532         0.0  0.9751248   
3   LASSO (YourCV10 w/ rescaling)  -0.043951258  0.94682777  1.7853748   
4  LASSO (YourCV10 w/o rescaling)    -0.0472358   0.9605377  1.8001353   

          b3           b4            b5  
0         NA           NA            NA  
1  2.7999191  -0.41411597  -0.024035463  
2  1.9452907         -0.0          -0.0  
3  2.7038982  -0.27762178          -0.0  
4  2.7189517  -0.28917325          -0.0

In [253]:
table2 = pd.DataFrame(
    np.array([['Null', 'NA', 'NA', RMSE_null, R2_null, E_RMSE_null_test, E_R2_null_test],
              ['Full', 'NA', bh_full, RMSE_full, R2_full, E_RMSE_full_test, E_R2_full_test],
              ['LASSO (LassoCV10)', 1.0, bh_lasso, RMSE_lasso, R2_lasso, E_RMSE_lasso_test, E_R2_lasso_test],
              ['LASSO (YourCV10 w/ rescaling)', alpha_w, bh_w, RMSE_lasso_w, R2_lasso_w, E_RMSE_lasso_w_test, E_R2_lasso_w_test],
              ['LASSO (YourCV10 w/o rescaling)', alpha_wo, bh_wo, RMSE_lasso_wo, R2_lasso_wo, E_RMSE_lasso_wo_test, E_R2_lasso_wo_test]]
             ),
    columns=['Goodness of fit and prediction', 'lambda', '|b|', 'RMSE fit', 'R2 fit', 'E(RMSE test)', 'E(R2 test)'])
table2

Goodness of fit and prediction lambda                |b|  \
0                            Null     NA                 NA   
1                            Full     NA  6.213876912370324   
2               LASSO (LassoCV10)    1.0  2.920415461063385   
3   LASSO (YourCV10 w/ rescaling)  0.008  5.713722497224808   
4  LASSO (YourCV10 w/o rescaling)    0.1  5.768797874450684   

             RMSE fit      R2 fit        E(RMSE test)  E(R2 test)  
0  4.7176467919569935         0.0  4.7176467919569935         0.0  
1   6.029924474341263  0.63473547   6.048960244864014   0.6347354  
2   5.255187242186472  0.24147923   5.268112364860296   0.2414792  
3   5.914790361934628    0.572884   5.933071693623774  0.57288396  
4  5.9300496791154576   0.5810127   5.948427765149146  0.58101267

In [254]:
# test
a = np.ones((3, 1))
b = np.ones((3,))

In [255]:
a.shape, b.shape

((3, 1), (3,))

In [261]:
a.reshape((-1,)).shape

(3,)

In [288]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
c = np.array([2,4]).reshape(1,2)
#a.dot(b)

In [283]:
a

array([[1, 2],
       [3, 4]])

In [277]:
a.shape

(2,)

In [291]:
a.dot(c.T)

array([[10],
       [22]])

In [293]:
np.matmul(a,c.T)

array([[10],
       [22]])